### ISSUE TITLE
libepoxy tries to use GLX on Wayland when running in apitrace with libGL

### ISSUE THREAD

**Issue by linkmauve** [anholt/libepoxy#68]
apitrace prints the following message:

```
glXGetCurrentContext() not found in libGL.so.1: /usr/bin/../lib/apitrace/wrappers/egltrace.so: undefined symbol: glXGetCurrentContext
```

Here is the backtrace from where libepoxy calls `exit()`:

```
Breakpoint 1, 0x00007ffff6faccd0 in _exit () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6faccd0 in _exit () from /usr/lib/libc.so.6
#1  0x00007ffff6f29f3b in __run_exit_handlers () from /usr/lib/libc.so.6
#2  0x00007ffff6f29fd5 in exit () from /usr/lib/libc.so.6
#3  0x00007ffff72f051a in do_dlsym (handle=<optimized out>, lib_name=0x7ffff7344b20 "libGL.so.1", name=0x7ffff7362b77 <entrypoint_strings+1143> "glXGetCurrentContext", exit_on_fail=<optimized out>)
    at dispatch_common.c:262
#4  0x00007ffff73413c6 in glx_provider_resolver (entrypoints=0x7fffffffda2c, providers=0x7fffffffda30, name=0x7ffff7362b77 <entrypoint_strings+1143> "glXGetCurrentContext") at glx_generated_dispatch.c:562
#5  glx_single_resolver (provider=provider@entry=GLX_10, entrypoint_offset=entrypoint_offset@entry=1143) at glx_generated_dispatch.c:590
#6  0x00007ffff7342c26 in epoxy_glXGetCurrentContext_resolver () at glx_generated_dispatch.c:903
#7  epoxy_glXGetCurrentContext_global_rewrite_ptr () at glx_generated_dispatch.c:1425
#8  0x00007ffff72f0553 in epoxy_current_context_is_glx () at dispatch_common.c:412
#9  0x00007ffff72f060d in epoxy_is_desktop_gl () at dispatch_common.c:282
#10 0x00007ffff72f6635 in gl_provider_resolver (name=0x7ffff7354ad8 <entrypoint_strings+16120> "glGenTextures", providers=0x7ffff734ef78 <providers>, entrypoints=0x7ffff734ef72 <entrypoints>)
    at gl_generated_dispatch.c:7319
#11 0x00007ffff73240b9 in epoxy_glGenTextures_resolver () at gl_generated_dispatch.c:18408
#12 epoxy_glGenTextures_global_rewrite_ptr (n=1, textures=0x7fffffffdb54) at gl_generated_dispatch.c:46117
#13 0x00000000004009c0 in main ()
```

I originally thought this was an apitrace bug, see https://github.com/apitrace/apitrace/issues/380

**Comment by jrfonseca** [comment]
`epoxy_current_context_is_glx`'s code looks brittle: it invokes `dlsym(NULL, "glXGetCurrentContext")`, but instead of using that symbol directly, it invokes its version of `glXGetCurrentContext` which might do something different.

I suspect that what's happening here is that:
- libGL.so is being loaded, so `dlsym(NULL, "glXGetCurrentContext")` is non-null
- epoxy_glXGetCurrentContext_resolver invokes `dlopen("libGL.so")` instead of `dlsym(NULL, "glXGetCurrentContext")`
- apitrace is intercepting `dlopen("libGL.so") so it returns `egltrace.so`, but `egltrace.so` has no `glXGetCurrentContext`, so `epoxy_glXGetCurrentContext_resolver` aborts

There's no right or wrong here: both apitrace and libepoxy are trying to be too smart, trying to guess things about the application.

But if libepoxy is modified such  that `epoxy_current_context_is_glx` and `epoxy_glXGetCurrentContext_resolver` get the  glXGetCurrentContext symbol in a consistent manner, then it can protect itself against this sort of issues.

I also think that, rather than trying to automagically detect which API (GLX/EGL, etc) is being used by the applicaiton, it would be much more robust have the application explicitly inform `libepoxy` so it doesn't have to guess.  There are many situations where `eglGetCurrentContext` might be implemented on top of `glXGetCurrentContext`, making it impossible to distinguish which EGL/GLX API is actually used by the application.

**Comment by yaronct** [comment]
@linkmauve, @jrfonseca: Could u plz try [my fork](https://github.com/yaronct/libepoxy) (branch "master") and tell me if the problem is there too? I've fixed some bugs in my fork, specifically for EGL, and I have the feeling that your problem won't exist there. I'm not even openning a Pull Request for them because I have a very old open Pull Request here that hasn't been pulled yet. If there's still a problem I'll look into it.

**Comment by yaronct** [comment]
@jrfonseca: I don't think there's a problem with trying to automagically detect which API is used. True - EGL is sometimes implemented on top of GLX (or other), but if u first try to detect EGL (rather than GLX) then it should work. That's what I do in my fork.

**Comment by sesse** [comment]
Hi,

I tried the fork in question, and it doesn't make any change. With apitrace trace --api ./program, I still get:

apitrace: loaded into /usr/local/bin/apitrace
apitrace: unloaded from /usr/local/bin/apitrace
apitrace: loaded into /home/sesse/dev/program/program
apitrace: tracing to /home/sesse/dev/program/program.1.trace
apitrace: attempting to read configuration file: /home/sesse/.config/apitrace/gltrace.conf
apitrace: redirecting dlopen("libEGL.so.1", 0x1)
egl context=0xd7eaa0
apitrace: redirecting dlopen("libGL.so.1", 0x1)
glXGetCurrentContext() not found in libGL.so.1: /usr/local/bin/../lib/x86_64-linux-gnu/apitrace/wrappers/egltrace.so: undefined symbol: glXGetCurrentContext
apitrace: unloaded from /home/sesse/dev/program/program
glXGetCurrentContext() not found in libGL.so.1: /usr/local/bin/../lib/x86_64-linux-gnu/apitrace/wrappers/egltrace.so: undefined symbol: glXGetCurrentContext

which is exactly what I get with upstream libepoxy, too. This is with Qt to create the EGL context on Mesa 11.0 (desktop), FWIW.

**Comment by sesse** [comment]
Oh, and for me, this isn't Wayland—it's regular X11. (But I need EGL.)

**Comment by sesse** [comment]
Hm, I looked into it some more. It seems some other code was actually at fault here, so with the fork, it _does_ work (after that fix in non-epoxy code).

**Comment by yaronct** [comment]
@sesse: :)

**Comment by sesse** [comment]
Well, you could argue perhaps it's epoxy… my code needs to get some sort of identifier for the current context (to know where it can share FBOs) and does:

        void *ret = (void *)glXGetCurrentContext();
        if (ret != NULL) {
                return ret;
        }
        return (void *)eglGetCurrentContext();

The first call makes the entire code exit. And I don't know of any other way of checking whether I'm in GLX or EGL mode.

**Comment by yaronct** [comment]
OK is **is** a problem with Epoxy, because when u call "glXGetCurrentContext()", if resolving the function fails, it crashes. I'm working on a workaround.

**Comment by yaronct** [comment]
@sesse: Ok, first of all, your logic is problematic, coz as @jrfonseca has pointed out, EGL may b implemented on top of GLX. Therefore, u should first try "eglGetCurrentContext" and only if it returns null go for glXGetCurrentContext.

Now, that still won't work, because when u call e.g. "eglGetCurrentContext" and resolving it fails, Epoxy crashes. I'm working on a workaround for that. In the meantime, I've created another workaround for u - plz check [my updated fork](https://github.com/yaronct/libepoxy) (branch "master"). You'll find there a function "bool epoxy_current_context_is_egl()" which returns true if the current context is EGL and false otherwise (i.e. GLX/WGL/etc). Note, though, that it assumes that **there is** some kind of current desktop OpenGL / OpenGL ES context (in your case, EGL or GLX). If this is not the case for u (that is, it's possible that there's neither EGL nor GLX current context) - plz tell me and I'll work out a better fix for u.

**Comment by bgamari** [comment]
Wasn't this fixed in f81274b12470a0ce8678465112998708f63c3559?

**Comment by ebassi** [comment]
No feedback in 11 months ⇒ closing.

**Comment by linkmauve** [comment]
Fyi this bug is now fixed by dbfa4b209c0712b67dfeb8366c2ebe8503063b52, thanks a lot!

**Comment by Mis012** [comment]
I can't seem to find a way to *not* reproduce this bug... using a debugging build of Gtk to force EGL on x11 used to work, but doesn't seem to anymore (or maybe I was lucky with my setup)

last tested on Tumbleweed Gnome Shell wayland, and alpine linux Gnome shell wayland / openbox x11

**Comment by Mis012** [comment]
ok, so I tried compiling libepoxy without glx support so that it can't possibly try to use glx... and now I get `symbol lookup error: /lib64/libgtk-4.so.1: undefined symbol: epoxy_glXMakeContextCurrent`

**Comment by ebassi** [comment]
That has nothing to do with libepoxy: GTK4 cannot be built without GLX support unless it's built without its X11 backend.

**Comment by Mis012** [comment]
yeah, I got that sorted... didn't mean to post that in this thread

but while I managed to work around the original issue by compiling Gtk without x11 support and libepoxy without Glx support, it would be nice if it could somehow be fixed
